#!/usr/bin/env node
// ---------------------------------------------------------------------------
// Turn a persona run into a report a developer can act on: USER_TESTING.md.
//
// The user-tester team (tests/battery/personas/) does not assert its way to a
// pass or a fail. It USES the product and writes down what confused, stalled,
// broke or excluded somebody — which is evidence for a person to weigh, not a
// gate. This script is the other half of that: it collects every observation
// from the run, deduplicates across personas, sorts by severity, and writes one
// document with the worst things first.
//
// WHY A COMMITTED FILE RATHER THAN A CI ARTEFACT
//
// An artefact inside a zip on a build that has scrolled off the first page is a
// report nobody reads. USER_TESTING.md is in the repo, it diffs, and a change
// in what the testers can no longer do shows up in a pull request next to the
// code that caused it.
//
// Usage:
//   node scripts/persona-report.mjs            # write USER_TESTING.md
//   node scripts/persona-report.mjs --check    # exit 1 if the file is stale
// ---------------------------------------------------------------------------
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT_DIR = path.join(process.cwd(), "playwright-report", "personas", "observations");
const OUT = path.join(process.cwd(), "USER_TESTING.md");
const CHECK = process.argv.includes("--check");

const SEVERITIES = ["blocker", "major", "minor", "polish"];
const SEVERITY_BLURB = {
  blocker: "Somebody could not do the job they came to do, or the product errored while they were using it.",
  major: "They got there, but the product misled them, hid something they needed, or risked a mistake they cannot undo.",
  minor: "Friction. Worth fixing when the area is next open.",
  polish: "Noted in passing.",
};
const KIND_LABEL = {
  broke: "it broke",
  stuck: "could not carry on",
  confusing: "could not tell what was happening",
  unreadable: "beyond this person",
  fragile: "worked, but only just",
  slow: "slower than they wait",
};

// Each run writes into its own `run-<pid>` directory (see personas/tester.ts),
// so a run can never delete another one's findings. This reads the newest, and
// then deletes the rest: keeping them would mean the next report silently mixed
// two runs, which is the failure this whole arrangement exists to prevent.
function newestRunDir() {
  if (!existsSync(ROOT_DIR)) return null;
  const dirs = readdirSync(ROOT_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.startsWith("run-"))
    .map((entry) => path.join(ROOT_DIR, entry.name))
    .sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs);
  if (!dirs.length) return null;
  for (const stale of dirs.slice(1)) rmSync(stale, { recursive: true, force: true });
  return dirs[0];
}

const IN_DIR = newestRunDir();
if (!IN_DIR) {
  console.error("[persona-report] No observations found. Run: npm run test:personas");
  process.exit(CHECK ? 1 : 0);
}

const runs = readdirSync(IN_DIR)
  .filter((f) => f.endsWith(".json"))
  .map((f) => JSON.parse(readFileSync(path.join(IN_DIR, f), "utf8")));

if (runs.length === 0) {
  console.error("[persona-report] No observations found. Run: npm run test:personas");
  process.exit(CHECK ? 1 : 0);
}

// Group identical findings across personas: the same sentence from three people
// is one problem with three witnesses, and the witnesses are the argument for
// fixing it.
const findings = new Map();
for (const run of runs) {
  for (const o of run.observations) {
    const key = `${o.severity}|${o.what}`;
    const entry = findings.get(key) ?? { ...o, witnesses: [], screens: new Set() };
    if (!entry.witnesses.some((w) => w.persona === o.persona && w.journey === o.journey)) {
      entry.witnesses.push({ persona: o.persona, journey: o.journey, device: o.device });
    }
    entry.screens.add(o.where);
    if (o.evidence && !entry.evidence) entry.evidence = o.evidence;
    findings.set(key, entry);
  }
}

const all = [...findings.values()].sort(
  (a, b) =>
    SEVERITIES.indexOf(a.severity) - SEVERITIES.indexOf(b.severity) ||
    b.witnesses.length - a.witnesses.length ||
    a.what.localeCompare(b.what),
);

const bySeverity = (s) => all.filter((f) => f.severity === s);
const personas = [...new Set(runs.map((r) => r.persona.name))];
const journeysRun = runs.length;
const stopped = runs.filter((r) => r.status !== "passed");

const esc = (s) => String(s).replace(/\|/g, "\\|").replace(/\n+/g, " ").trim();

const lines = [];
lines.push("# What the user testers found");
lines.push("");
lines.push(
  "Generated by `npm run test:personas` from `tests/battery/personas/`. **Do not edit by hand** — it is rewritten on every run.",
);
lines.push("");
lines.push(
  "A team of personas — a platform operator, teachers, a school business manager, parents, children in each of the three registers, and a fuzzing bot in a child's session — uses the real product in their own school (Bramblewood Academy, `prisma/seed-personas.ts`) on their own device, and writes down anything that confused them, stalled them, broke, or excluded them. This is what they said, worst first.",
);
lines.push("");
lines.push("Severities are the testers' own, and they mean:");
lines.push("");
for (const s of SEVERITIES) lines.push(`- **${s}** — ${SEVERITY_BLURB[s]}`);
lines.push("");
lines.push("## The run");
lines.push("");
lines.push(`- **${journeysRun}** journeys, **${personas.length}** testers.`);
lines.push(`- **${all.length}** distinct findings: ` + SEVERITIES.map((s) => `${bySeverity(s).length} ${s}`).join(" · ") + ".");
if (stopped.length) {
  lines.push(
    `- **${stopped.length}** journey(s) ended early: ` +
      stopped.map((r) => `${r.persona.name} — “${r.journey}”`).join("; ") +
      ". A journey ends early when a tester hits a blocker; everything after it in that journey is untested.",
  );
} else {
  lines.push("- Every journey ran to the end.");
}
lines.push("");

// A "start here" list, because a report that opens with 40 findings gets read
// as a wall rather than as work. Blockers and majors only, in order, with the
// witness count — three testers hitting the same thing is the argument for
// doing it first.
// One control that is too small is a finding; fifteen of them on one screen is
// still ONE finding with fifteen examples, and listing them separately buries
// everything else. They are collapsed here rather than in the tester, so the
// per-control detail stays in the run's JSON for whoever fixes it.
const TARGET_SIZE = /^“(.+)” is (\d+)×(\d+)px — under the (\d+)px/;
const isTargetSize = (f) => TARGET_SIZE.test(f.what);

function collapseTargets(group) {
  const targets = group.filter(isTargetSize);
  const rest = group.filter((f) => !isTargetSize(f));
  if (targets.length < 2) return group;
  const byFloor = new Map();
  for (const f of targets) {
    const [, name, w, h, floor] = f.what.match(TARGET_SIZE);
    const bucket = byFloor.get(floor) ?? { floor, items: [], witnesses: new Map(), screens: new Set(), severity: f.severity, kind: f.kind };
    bucket.items.push(`${name} (${w}×${h})`);
    for (const wit of f.witnesses) bucket.witnesses.set(`${wit.persona}|${wit.journey}`, wit);
    for (const screen of f.screens) bucket.screens.add(screen);
    byFloor.set(floor, bucket);
  }
  const merged = [...byFloor.values()].map((b) => ({
    severity: b.severity,
    kind: b.kind,
    what:
      `${b.items.length} controls are smaller than the ${b.floor}px this person can reliably hit` +
      (b.floor === "64" ? " (SAFEGUARDING rule 18, anything a child taps)" : "") +
      `: ${b.items.slice(0, 12).join(", ")}` +
      (b.items.length > 12 ? `, and ${b.items.length - 12} more` : "") +
      ".",
    witnesses: [...b.witnesses.values()],
    screens: b.screens,
    evidence: undefined,
  }));
  return [...merged, ...rest];
}

const worst = collapseTargets([...bySeverity("blocker"), ...bySeverity("major")]).sort(
  (a, b) => SEVERITIES.indexOf(a.severity) - SEVERITIES.indexOf(b.severity) || b.witnesses.length - a.witnesses.length,
);
if (worst.length) {
  lines.push("## Start here");
  lines.push("");
  lines.push(
    "Everything a tester could not do, or was misled by. Ordered by severity, then by how many of them hit it. Controls that are simply too small are collapsed into one line per floor — they are one problem with many examples, and the per-control sizes are in the sections below.",
  );
  lines.push("");
  for (const f of worst) {
    const witnesses = f.witnesses.length > 1 ? ` _(${f.witnesses.length} testers)_` : "";
    lines.push(`- [ ] **${f.severity}** — ${esc(f.what)}${witnesses}`);
  }
  lines.push("");
}

// What KIND of trouble this run was, in one line — a run that is all "could not
// tell what was happening" is a copy problem, and one that is all "beyond this
// person" is a design-system problem. They get fixed by different people.
const kinds = new Map();
for (const f of all) kinds.set(f.kind, (kinds.get(f.kind) ?? 0) + 1);
if (kinds.size) {
  lines.push("## The shape of it");
  lines.push("");
  for (const [kind, n] of [...kinds.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`- **${KIND_LABEL[kind] ?? kind}** — ${n}`);
  }
  lines.push("");
}

for (const severity of SEVERITIES) {
  const group = bySeverity(severity);
  if (!group.length) continue;
  lines.push(`## ${severity[0].toUpperCase()}${severity.slice(1)} (${group.length})`);
  lines.push("");
  lines.push(`> ${SEVERITY_BLURB[severity]}`);
  lines.push("");
  for (const f of group) {
    const who = f.witnesses.map((w) => w.persona).join(", ");
    lines.push(`### ${esc(f.what)}`);
    lines.push("");
    lines.push(`- **Who hit it:** ${esc(who)}`);
    lines.push(`- **Doing:** ${f.witnesses.map((w) => esc(w.journey)).join("; ")}`);
    lines.push(`- **Where:** ${[...f.screens].slice(0, 4).map(esc).join(" · ")}`);
    lines.push(`- **Kind:** ${KIND_LABEL[f.kind] ?? f.kind}`);
    if (f.evidence) lines.push(`- **Evidence:** ${esc(f.evidence).slice(0, 400)}`);
    lines.push("");
  }
}

lines.push("## Where this goes next");
lines.push("");
lines.push(
  "An observation here is a tester's judgement, not a triaged defect. The ones that survive being checked against the code get an ID in [`FINDINGS.md`](./FINDINGS.md) and a repro test in `tests/battery/findings/` that asserts the intended behaviour and **fails on purpose** until it is built. The rest stay here until somebody decides they are worth acting on — which is the point of writing them down in the tester's own words rather than as a failing assertion.",
);
lines.push("");
lines.push("Two things worth knowing before acting on any of it:");
lines.push("");
lines.push(
  "- **The testers can be wrong.** They have been: a substring match once had a persona reporting a child's name on the operator console (it was the \"bo\" in \"about\"), and a count taken before hydration once had one reporting that a screen had no file upload when it has one. Check the claim before you change the code. `TEST_PLAN.md` B7 lists every mistake this harness has made and what was changed so it cannot make it again.",
);
lines.push(
  "- **A journey that stopped early tested nothing after that point.** The run summary above says which, and those journeys are the first place to look for findings that have not been made yet.",
);
lines.push("");
lines.push("## Who the testers are");
lines.push("");
lines.push("| Tester | Device | Reads | Hits targets down to |");
lines.push("| --- | --- | --- | --- |");
for (const run of runs.filter((r, i, xs) => xs.findIndex((x) => x.persona.id === r.persona.id) === i)) {
  const p = run.persona;
  lines.push(`| ${esc(p.name)} | ${esc(p.device.label)} (${p.device.width}×${p.device.height}) | ${p.reads} | ${p.minTarget}px |`);
}
lines.push("");
lines.push("Full descriptions in `tests/battery/personas/team.ts`; the school they work in is `prisma/seed-personas.ts`.");
lines.push("");
lines.push("## How to reproduce any of this");
lines.push("");
lines.push("```bash");
lines.push("npm run db:seed:test && npm run db:seed:personas   # the testers' school");
lines.push("npm run test:personas                              # run the team, rewrite this file");
lines.push("npx playwright test -c playwright.battery.config.ts --project=personas \\");
lines.push('  --grep "set a quiz"                              # one journey');
lines.push("```");
lines.push("");
lines.push(
  "Each journey attaches its own findings to the Playwright HTML report (`playwright-report/battery`), with a screenshot at the point of failure for anything that stopped a tester.",
);
lines.push("");

const body = lines.join("\n");

if (CHECK) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== body) {
    console.error("[persona-report] USER_TESTING.md is out of date — run `npm run test:personas`.");
    process.exit(1);
  }
  console.log("[persona-report] USER_TESTING.md is current.");
  process.exit(0);
}

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(
  `[persona-report] USER_TESTING.md written — ${all.length} findings from ${journeysRun} journeys ` +
    `(${SEVERITIES.map((s) => `${bySeverity(s).length} ${s}`).join(", ")}).`,
);
